---
apiVersion: v1
kind: Service
metadata:
  name: catalogd-catalogserver
  namespace: openshift-catalogd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8083
  selector:
    control-plane: controller-manager
